config/routes.rb
YelpClone::Application.routes.draw do
  root 'pages#front'
  get '/home', to: "businesses#index"
  get '/sign_in', to: "sessions#new"
  post '/sign_in', to: "sessions#create"
  get '/logout', to: "sessions#destroy"

  resources :businesses, only: [:show, :new, :create] do
    resources :reviews, only: [:create]
  end
  resources :users, only: [:new, :create, :show, :index]

  get 'ui(/:action)', controller: 'ui'

end

app/models/business.rb
class Business < ActiveRecord::Base
  validates_presence_of :name
  validates_uniqueness_of :name
  has_many :reviews

  def recent_reviews
    reviews.order(created_at: :desc).limit(10)
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :business
  validates_presence_of :body, :user, :business
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :username, :password
  validates_uniqueness_of :username
  has_secure_password validations: false
  has_many :reviews

  def recent_reviews
    reviews.order(created_at: :desc).limit(10)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  before_action :redirect_if_not_logged_in

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    end
  end

  def redirect_if_not_logged_in
    unless current_user
      if params[:controller] == 'businesses' and params[:action] == 'index'
        redirect_to root_path
      else
        flash[:danger] = "You must first login"
        redirect_to sign_in_path
      end
    end
  end
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  def index
    @businesses = Business.all
  end

  def new
    @business = Business.new
  end

  def create
    @business = Business.new(name: params[:business][:name], description: params[:business][:description])
    if @business.save
      flash[:success] = "New business added"
      redirect_to business_path(@business)
    else
      flash[:danger] = "Please fix your input and resubmit"
      render :new
    end
  end

  def show
    @business = Business.find(params[:id])
    @review = Review.new
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_filter :redirect_if_not_logged_in
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @business = Business.find(params[:business_id])
    @review = Review.new(business: @business, user: current_user, body: params[:review][:body])
    if @review.save
      flash[:success] = "Thank you for your review on #{@business.name}" 
      redirect_to business_path(@business)
    else
      flash[:danger] = "Please type a review before hitting Submit"
      render "businesses/show"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :redirect_if_not_logged_in, only: [:new, :create]

  def new
    redirect_to home_path if current_user
  end

  def create
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      flash[:success] = "Welcome #{@user.username}"
      redirect_to home_path
    else
      session[:user_id] = nil
      flash[:danger] = "Invalid username and/or password"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have logged out"
    redirect_to root_path
  end
end

app/controllers/ui_controller.rb
class UiController < ApplicationController
  before_filter do
    redirect_to :root if Rails.env.production?
  end

  layout "application"

  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :redirect_if_not_logged_in, except: [:show, :index]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "You have successfully registered. Please sign in below"
      redirect_to sign_in_path
    else
      flash[:danger] = "Please enter valid details below"
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.all
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/businesses/index.html.haml
%article.business_list
  %header.business
    .container
      .row
        .col-sm-10.col-sm-offset-1
          %h1
            List of all Businesses:
            .pull-right
              = link_to "+ Add a New Business", new_business_path, class: 'btn btn-danger'
          %ul
            - @businesses.each do |business|
              %li.h3= link_to "#{business.name}", business_path(business.id)

app/views/businesses/new.html.haml
%section.add_business
  .container
    .row
      .col-md-10.col-md-offset-1
        = bootstrap_form_for(@business, layout: :horizontal, label_col: "col-sm-3", control_col: "col-sm-6") do |f|
          %header.h1.col-md-offset-3
            Add a New Business
          %fieldset
            .form-group
              = f.text_field :name, label: "Business Name"
            .form-group
              = f.text_area :description, label: "Description of Business", rows: 8

          %fieldset.actions.form-group
            .col-sm-6.col-md-offset-3
              = f.submit "Add Business", class: "btn btn-default"

app/views/businesses/show.html.haml
%article.business
  .container.business_info
    .row
      .col-sm-10.col-sm-offset-1
        %header
          %h3
            = @business.name
        %br
        %p
          = @business.description

%section.reviews.container
  .row
    .col-sm-10.col-sm-offset-1
      = bootstrap_form_for [@business,@review], class: "col-sm-8" do |r|
        = r.text_area :body, label: 'Review this business', placeholder: "Start your review...", rows: 6
        = r.submit "Submit", class: "btn"
        &nbsp
        = link_to "Cancel"
      %header
        %h3 
          = "User Reviews (#{@business.reviews.count})"
          Showing the Most Recent 10 Reviews
      %ul
        - @business.recent_reviews.each do |review|
          %article.review
            %li.row
              .col-sm-2
                %p
                  by
                  = link_to review.user.username, user_path(review.user), id: "user_#{review.user.id}"
              .col-sm-8
                %p
                  = review.body

app/views/layouts/application.html.haml
!!! 5
%html(lang="en-US")
  %head
    %title YelpClone - a business review service
    %meta(charset="UTF-8")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    = csrf_meta_tag
    = stylesheet_link_tag "application", media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag "application", 'data-turbolinks-track' => true
  %body
    %header
      = render 'shared/header'
    %section.content.clearfix
      = render 'shared/messages'
      = yield
    %footer
      &copy 2016 YelpClone

app/views/pages/front.html.haml
%section.site_title
  %h1
    = link_to "Register now", new_user_path
    to find Reviews on Local Businesses
  %p.sign_up
  %p.sign_in
    Already have an account? Please
    = link_to "Sign In", sign_in_path
    

app/views/shared/_header.html.haml
%section#top-header.row
  %h1.col-md-2
    = link_to image_tag("header_print.gif"), home_path
  %ul.col-md-4.clearfix
    %li= link_to "User Profiles", users_path if current_user
  #user_links.pull-right
    %ul
      %li
        %a
          - if current_user
            = link_to "Logout", logout_path, id: "header_logout"
          - else
            = link_to "Sign Up", new_user_path, id: "header_sign_up"
            = link_to "Login", sign_in_path, id: "header_login"

app/views/shared/_messages.html.haml
- flash.each do |name, msg|
  %div(class="alert alert-#{name}")
    %a.close(data-dismiss='alert') &#215;
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/ui/add_business.html.haml
%section.add_business
  .container
    .row
      .col-md-10.col-md-offset-1
        %form.form-horizontal
          %header.h1.col-md-offset-3
            Add a New Business
          %fieldset
            .form-group
              %label.control-label.col-sm-3 Business Name
              .col-sm-3
                %input.form-control(type="text")
            .form-group
              %label.control-label.col-sm-3 Description
              .col-sm-6
                %textarea.form-control(rows="8")

          %fieldset.actions.form-group
            .col-sm-6.col-md-offset-3
              %input(type="submit" value="Add Business" class="btn btn-default")

app/views/ui/business.html.haml
%article.business
  .container.business_info
    .row
      .col-sm-10.col-sm-offset-1
        %header
          %h3 Mr Chippy
        %br
        %p A take away shop which sells fish and chips.

%section.reviews.container
  .row
    .col-sm-10.col-sm-offset-1
      %form
        %fieldset
          .form-group
            %label Review this business
            .row
              .col-sm-8
                %textarea.form-control(name="" rows="6" value="Start your review...")
        %fieldset.form-group.actions.clearfix
          %input(type="submit" value="Submit" class="btn")
          %a(href="") Cancel
      %header
        %h3 User Reviews (253)
      %ul
        - 8.times do
          %article.review
            %li.row
              .col-sm-2
                %p by <a href="">John A. Zoidberg</a>
              .col-sm-8
                %p In my opinion, this is one of the best local takeaway shops.

app/views/ui/business_list.html.haml
%article.business_list
  %header.business
    .container
      .row
        .col-sm-10.col-sm-offset-1
          %h1 List of all Businesses:
          %ul
            - 6.times do
              %li.h3= link_to "Mr Chippy"

app/views/ui/home.html.haml
%section.site_title
  %h1
    = link_to "Register now"
    to find Reviews on Local Businesses
  %p.sign_up
  %p.sign_in
    Already have an account? Please
    = link_to "Sign In"
    

app/views/ui/index.html.haml
%section.ui-index
  %ul
    - Dir.glob('app/views/ui/*.html.haml').sort.each do |file|
      - wireframe = File.basename(file,'.html.haml')
      -  unless wireframe == 'index' || wireframe.match(/^_/)
        %li= link_to wireframe.titleize, action: wireframe unless wireframe == 'index'

app/views/ui/register.html.haml
%section.register.container
  .row
    .col-sm-10.col-sm-offset-1
      %form.form-horizontal
        %header
          %h1.col-sm-offset-2 Register
        %fieldset
          .form-group
            %label.control-label.col-sm-2 Username
            .col-sm-6
              %input.form-control(type="text")
          .form-group
            %label.control-label.col-sm-2 Password
            .col-sm-6
              %input.form-control(type="password")
        %fieldset.actions.control-group.col-sm-offset-2
          .controls
            %input(type="submit" value="Sign Up" class="btn btn-default")

app/views/ui/sign_in.html.haml
%section.sign_in.container
  .row
    .col-sm-10.col-sm-offset-1
      %form.sign_in
        %header
          %h1 Sign in
        %fieldset
          .form-group
            %label Username
            .row
              .col-sm-4
                %input.form-control(type="text")
          .form-group
            %label Password
            .row
              .col-sm-4
                %input.form-control(type="password")
        %fieldset.form-group.action
          %input(type="submit" value="Sign in" class="btn btn-default")

app/views/ui/user.html.haml
%section.user
  %article
    .container
      .row
        .col-sm-10.col-sm-offset-1
          %header
            %h2 Profile of: John Doe

%section.user_reviews.container
  .row
    .col-sm-10.col-sm-offset-1
      %header
        %h3 Total Reviews (12)
      %ul
        - 12.times do
          %article.review
            %li.row
              .col-sm-2
                %p Review of: </br><a href="">Mr Chippy</a>
              .col-sm-8
                %p In my opinion, this is one of the best local takeaway shops.

app/views/users/index.html.haml
%article.business_list
  %header.business
    .container
      .row
        .col-sm-10.col-sm-offset-1
          %h1
            List of all Users:
          %ul
            - @users.each do |user|
              %li.h3= link_to "#{user.username}", user_path(user.id), id: "user_#{user.id}"

app/views/users/new.html.haml
%section.register.container
  .row
    .col-sm-10.col-sm-offset-1
      = bootstrap_form_for(@user, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-6") do |f|
        %header
          %h1.col-sm-offset-2 Register
        %fieldset
          = f.text_field :username, label: "Username"
          = f.password_field :password, label: "Password"
        %fieldset.actions.control-group.col-sm-offset-2
          .controls
            = f.submit "Sign Up", class: "btn btn-default", id: "register_button"

app/views/users/show.html.haml
%section.user
  %article
    .container
      .row
        .col-sm-10.col-sm-offset-1
          %header
            %h2
              Profile of:
              = @user.username

%section.user_reviews.container
  .row
    .col-sm-10.col-sm-offset-1
      %header
        %h3 
          = "Total Reviews by User (#{@user.reviews.count})"
          Showing the Most Recent 10 Reviews
      %ul
        - @user.recent_reviews.each do |review|
          %article.review
            %li.row
              .col-sm-2
                %p
                  Review of: 
                  = link_to review.business.name, business_path(review.business)
              .col-sm-8
                %p
                  = review.body